1 = "0xFF30CF"
2 = "0xFF18E7"
3 = "0xFF7A85"
4 = "0xFF10EF"
5 = "0xFF38C7"
6 = "0xFF5AA5"
7 = "0xFF42BD"
8 = "0xFF4AB5"
9 = "0xFF52AD"
0 = "0xFF6897"
nav_cfg = "0xFF22DD"
nav_up = "0xFF02FD"
nav_left = "0xFFE01F"
nav_enter = "0xFFA857"
nav_right = "0xFF906F"
nav_back = "0xFFB04F"
nav_down = "0xFF9867"
play = "0xFF629D"
stop = "0xFFC23D"
pause = "0xFF629D"
vol- = "0xFFA25D"
"vol+" = "0xFFE21D"
